postagliste_en= {
"CC":"coordinating conjunction",
"CD":"cardinal digit",
"DT":"determiner",
"EX":"existential there (like: 'there is' ... think of it like 'there exists')",
"FW":"foreign word",
"IN":"preposition/subordinating conjunction",
"JJ":"adjective	'big'",
"JJR":"adjective, comparative	'bigger'",
"JJS":"adjective, superlative	'biggest'",
"LS":"list marker	1)",
"MD":"modal	could, will",
"NN":"noun, singular 'desk'",
"NNS":"noun plural	'desks'",
"NNP":"proper noun, singular	'Harrison'",
"NNPS":"proper noun, plural	'Americans'",
"PDT":"predeterminer	'all the kids'",
"POS":"possessive ending	parent\'s",
"PRP":"personal pronoun	I, he, she",
"PRP$":"possessive pronoun	my, his, hers",
"RB":"adverb	very, silently,",
"RBR":"adverb, comparative	better",
"RBS":"adverb, superlative	best",
"RP":"particle	give up",
"SYM":"symbol",
"TO":"to	go 'to' the store.",
"UH":"interjection	errrrrrrrm",
"VB":"verb, base form	take",
"VBD":"verb, past tense	took",
"VBG":"verb, gerund/present participle	taking",
"VBN":"verb, past participle	taken",
"VBP":"verb, sing. present, non-3d	take",
"VBZ":"verb, 3rd person sing. present	takes",
"WDT":"wh-determiner	which",
"WP":"wh-pronoun	who, what",
"WP$":"possessive wh-pronoun	whose",
"WRB":"wh-abverb	where, when"
}

postagliste_fr={
    	
"ADJ":"adjectif",
"ADJWH":"adjectif interrogatif",
"ADV":"adverbe",
"ADVWH":"adverbe interrogatif",
"CC":"conjonction de coordination",
"CL":"pronom clitique",
"CLO":"pronom clitique objet",
"CLR":"pronom clitique réfléchi",
"CLS":"pronom clitique sujet",
"CS":"conjonction de subordination",
"DET":"déterminant",
"DETWH":"déterminant interrogatif",
"ET":"mot tiré d'une langue étrangère",
"I":"interjection",
"N":"nom",
"NC":"nom commun",
"NPP":"nom propre",
"P":"préposition",
"P+D":"forme contractée préposition et déterminant",
"P+PRO":"forme contractée préposition et pronom",
"PUNC":"ponctuation",
"PREF":"préfixe",
"PRO":"pronom",
"PROREL":"pronom relatif",
"PROWH":"pronom interrogatif",
"V":"verbe",
"VIMP":"forme verbale à l'impératif",
"VINF":"forme verbale à l'infinitif",
"VPP":"participe passé",
"VPR":"participe présent",
"VS":"forme verbale au subjonctif"
}
